version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    depends_on:
      - backend

  db:
    image: postgres:13
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
